//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movy()
        {
            this.Chapters = new HashSet<Chapter>();
            this.MoviesRelateCategories = new HashSet<MoviesRelateCategory>();
        }
    
        public int Id { get; set; }
        public string MovieName { get; set; }
        public Nullable<System.DateTime> ProductionYear { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> DirectorId { get; set; }
        public Nullable<int> NumberOfChapter { get; set; }
        public Nullable<int> MovieQualityId { get; set; }
        public Nullable<int> MovieStatusId { get; set; }
        public Nullable<int> TranscriptId { get; set; }
        public Nullable<int> RateOneStar { get; set; }
        public Nullable<int> RateTwoStar { get; set; }
        public Nullable<int> RateThreeStar { get; set; }
        public Nullable<int> RateFourStar { get; set; }
        public Nullable<int> RateFiveStar { get; set; }
        public Nullable<int> ImdbScore { get; set; }
        public string Description { get; set; }
        public Nullable<int> NumberOfViewer { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chapter> Chapters { get; set; }
        public virtual Director Director { get; set; }
        public virtual MovieQuality MovieQuality { get; set; }
        public virtual MovieStatus MovieStatus { get; set; }
        public virtual Transcript Transcript { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoviesRelateCategory> MoviesRelateCategories { get; set; }
    }
}
